# Generated by Django 5.1.6 on 2025-02-26 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsPartage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomDocument', models.CharField(max_length=255)),
                ('Fichier', models.FileField(upload_to='documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_partage', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.utilisateur')),
            ],
        ),
    ]
