# Generated by Django 5.1.6 on 2025-02-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentsPartage',
            new_name='DocumentPartage',
        ),
    ]
